CREATE TABLE Subscription(
	  subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
	  encoded_id varchar(100),
	  payment_plan_id INT NOT NULL	  
);

CREATE UNIQUE INDEX encoded_id_index ON Subscription(encoded_id);