CREATE TABLE app_direct_user(
	  app_direct_user_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 10000, INCREMENT BY 1) PRIMARY KEY,
	  email varchar(100),
	  first_name varchar(100), 
	  last_name varchar(100),
	  open_id varchar(250),
	  uuid varchar(100)
);




CREATE TABLE Subscription(
	  subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
	  encoded_id varchar(100),
	  payment_plan_id INT NOT NULL	  
);

CREATE UNIQUE INDEX encoded_id_index ON Subscription(encoded_id);